import type { Metadata } from "next";
import localFont from "next/font/local";
import "./../styles/main.css";

export const metadata: Metadata = {
  title: "Demo UI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
